export type AgentRow = [string, string, string, string, string, string, string, string];

export const AGENT_ROWS: AgentRow[] = [
  ['aider-desk', 'AiderDesk', '$HOME/.aider-desk/skills', '.aider-desk/skills', '$HOME/.aider-desk', '', '', ''],
  ['amp', 'Amp', '$XDG_CONFIG_HOME/agents/skills', '.agents/skills', '$XDG_CONFIG_HOME/amp', '', '', ''],
  ['antigravity', 'Antigravity', '$HOME/.gemini/antigravity/skills', '.agents/skills', '$HOME/.gemini/antigravity', '', '', ''],
  ['antigravity-cli', 'Antigravity CLI', '$HOME/.gemini/antigravity-cli/skills', '.agents/skills', '$HOME/.gemini/antigravity-cli', '', '', ''],
  ['astrbot', 'AstrBot', '$HOME/.astrbot/data/skills', 'data/skills', '$HOME/.astrbot', '', '', ''],
  ['autohand-code', 'Autohand Code CLI', '$AUTOHAND_HOME/skills', '.autohand/skills', '$AUTOHAND_HOME', '', '', ''],
  ['augment', 'Augment', '$HOME/.augment/skills', '.augment/skills', '$HOME/.augment', '', '', ''],
  ['bob', 'IBM Bob', '$HOME/.bob/skills', '.bob/skills', '$HOME/.bob', '', '', ''],
  ['claude-code', 'Claude Code', '$CLAUDE_CONFIG_DIR/skills', '.claude/skills', '$CLAUDE_CONFIG_DIR', 'claude', '', ''],
  ['openclaw', 'OpenClaw', '$HOME/.openclaw/skills', 'skills', '$HOME/.openclaw|$HOME/.clawdbot|$HOME/.moltbot', '', '$HOME/.clawdbot/skills|$HOME/.moltbot/skills', ''],
  ['cline', 'Cline', '$HOME/.agents/skills', '.agents/skills', '$HOME/.cline', '', '', ''],
  ['codearts-agent', 'CodeArts Agent', '$HOME/.codeartsdoer/skills', '.codeartsdoer/skills', '$HOME/.codeartsdoer', '', '', ''],
  ['codebuddy', 'CodeBuddy', '$HOME/.codebuddy/skills', '.codebuddy/skills', '$HOME/.codebuddy', '', '', ''],
  ['codemaker', 'Codemaker', '$HOME/.codemaker/skills', '.codemaker/skills', '$HOME/.codemaker', '', '', ''],
  ['codestudio', 'Code Studio', '$HOME/.codestudio/skills', '.codestudio/skills', '$HOME/.codestudio', '', '', ''],
  ['codex', 'Codex', '$CODEX_HOME/skills', '.agents/skills', '$CODEX_HOME', 'codex', '$HOME/.agents/skills', '.codex/skills'],
  ['command-code', 'Command Code', '$HOME/.commandcode/skills', '.commandcode/skills', '$HOME/.commandcode', '', '', ''],
  ['continue', 'Continue', '$HOME/.continue/skills', '.continue/skills', '$HOME/.continue', '', '', ''],
  ['cortex', 'Cortex Code', '$HOME/.snowflake/cortex/skills', '.cortex/skills', '$HOME/.snowflake/cortex', '', '', ''],
  ['crush', 'Crush', '$HOME/.config/crush/skills', '.crush/skills', '$HOME/.config/crush', '', '', ''],
  ['cursor', 'Cursor', '$HOME/.cursor/skills', '.agents/skills', '$HOME/.cursor', '', '$HOME/.agents/skills|$HOME/.claude/skills|$HOME/.codex/skills', '.cursor/skills|.claude/skills|.codex/skills'],
  ['deepagents', 'Deep Agents', '$HOME/.deepagents/agent/skills', '.agents/skills', '$HOME/.deepagents', '', '', ''],
  ['devin', 'Devin for Terminal', '$XDG_CONFIG_HOME/devin/skills', '.devin/skills', '$XDG_CONFIG_HOME/devin', '', '', ''],
  ['dexto', 'Dexto', '$HOME/.agents/skills', '.agents/skills', '$HOME/.dexto', '', '', ''],
  ['droid', 'Droid', '$HOME/.factory/skills', '.factory/skills', '$HOME/.factory', '', '', ''],
  ['eve', 'Eve', '', 'agent/skills', '', '', '', ''],
  ['firebender', 'Firebender', '$HOME/.firebender/skills', '.agents/skills', '$HOME/.firebender', '', '', ''],
  ['forgecode', 'ForgeCode', '$HOME/.forge/skills', '.forge/skills', '$HOME/.forge', '', '', ''],
  ['gemini-cli', 'Gemini CLI', '$HOME/.gemini/skills', '.agents/skills', '$HOME/.gemini', '', '', ''],
  ['github-copilot', 'GitHub Copilot', '$HOME/.copilot/skills', '.agents/skills', '$HOME/.copilot', '', '', '.github/skills'],
  ['goose', 'Goose', '$XDG_CONFIG_HOME/goose/skills', '.goose/skills', '$XDG_CONFIG_HOME/goose', '', '', ''],
  ['grok', 'Grok Build', '$GROK_HOME/skills', '.grok/skills', '$GROK_HOME', '', '', ''],
  ['hermes-agent', 'Hermes Agent', '$HERMES_HOME/skills', '.hermes/skills', '$HERMES_HOME', '', '', ''],
  ['inference-sh', 'inference.sh', '$HOME/.inferencesh/skills', '.inferencesh/skills', '$HOME/.inferencesh', '', '', ''],
  ['jazz', 'Jazz', '$HOME/.jazz/skills', '.jazz/skills', '$HOME/.jazz', '', '', ''],
  ['junie', 'Junie', '$HOME/.junie/skills', '.junie/skills', '$HOME/.junie', '', '', ''],
  ['iflow-cli', 'iFlow CLI', '$HOME/.iflow/skills', '.iflow/skills', '$HOME/.iflow', '', '', ''],
  ['kilo', 'Kilo Code', '$HOME/.kilocode/skills', '.kilocode/skills', '$HOME/.kilocode', '', '', ''],
  ['kimchi', 'Kimchi', '$HOME/.config/kimchi/harness/skills', '.kimchi/skills', '$HOME/.config/kimchi', '', '', ''],
  ['kimi-code-cli', 'Kimi Code CLI', '$HOME/.agents/skills', '.agents/skills', '$HOME/.kimi-code|$HOME/.kimi', '', '', ''],
  ['kiro-cli', 'Kiro CLI', '$HOME/.kiro/skills', '.kiro/skills', '$HOME/.kiro', '', '', ''],
  ['kode', 'Kode', '$HOME/.kode/skills', '.kode/skills', '$HOME/.kode', '', '', ''],
  ['lingma', 'Lingma', '$HOME/.lingma/skills', '.lingma/skills', '$HOME/.lingma', '', '', ''],
  ['loaf', 'Loaf', '$HOME/.agents/skills', '.agents/skills', '$HOME/.loaf', '', '', ''],
  ['mcpjam', 'MCPJam', '$HOME/.mcpjam/skills', '.mcpjam/skills', '$HOME/.mcpjam', '', '', ''],
  ['minimax-code', 'MiniMax Code', '$HOME/.minimax/skills', '.minimax/skills', '$HOME/.minimax', '', '', ''],
  ['mistral-vibe', 'Mistral Vibe', '$VIBE_HOME/skills', '.vibe/skills', '$VIBE_HOME', '', '', ''],
  ['moxby', 'Moxby', '$HOME/.moxby/skills', '.moxby/skills', '$HOME/.moxby', '', '', ''],
  ['mux', 'Mux', '$HOME/.mux/skills', '.mux/skills', '$HOME/.mux', '', '', ''],
  ['opencode', 'OpenCode', '$XDG_CONFIG_HOME/opencode/skills', '.agents/skills', '$XDG_CONFIG_HOME/opencode', '', '$HOME/.claude/skills|$HOME/.agents/skills', '.opencode/skills|.claude/skills'],
  ['openhands', 'OpenHands', '$HOME/.openhands/skills', '.openhands/skills', '$HOME/.openhands', '', '', ''],
  ['ona', 'Ona', '$HOME/.ona/skills', '.ona/skills', '$HOME/.ona', '', '', ''],
  ['pi', 'Pi', '$HOME/.pi/agent/skills', '.pi/skills', '$HOME/.pi/agent', '', '', ''],
  ['posit-assistant', 'Posit Assistant', '$HOME/.posit/assistant/skills', '.posit/assistant/skills', '$HOME/.posit/assistant', '', '', ''],
  ['qoder', 'Qoder', '$HOME/.qoder/skills', '.qoder/skills', '$HOME/.qoder', '', '', ''],
  ['qoder-cn', 'Qoder CN', '$HOME/.qoder-cn/skills', '.qoder/skills', '$HOME/.qoder-cn', '', '', ''],
  ['qwen-code', 'Qwen Code', '$HOME/.qwen/skills', '.qwen/skills', '$HOME/.qwen', '', '', ''],
  ['replit', 'Replit', '$XDG_CONFIG_HOME/agents/skills', '.agents/skills', '', '', '', ''],
  ['reasonix', 'Reasonix', '$HOME/.reasonix/skills', '.reasonix/skills', '$HOME/.reasonix', '', '', ''],
  ['rovodev', 'Rovo Dev', '$HOME/.rovodev/skills', '.rovodev/skills', '$HOME/.rovodev', '', '', ''],
  ['roo', 'Roo Code', '$HOME/.roo/skills', '.roo/skills', '$HOME/.roo', '', '', ''],
  ['tabnine-cli', 'Tabnine CLI', '$HOME/.tabnine/agent/skills', '.tabnine/agent/skills', '$HOME/.tabnine', '', '', ''],
  ['terramind', 'Terramind', '$HOME/.terramind/skills', '.terramind/skills', '$HOME/.terramind', '', '', ''],
  ['tinycloud', 'Tinycloud', '$HOME/.tinycloud/skills', '.tinycloud/skills', '$HOME/.tinycloud', '', '', ''],
  ['trae', 'Trae', '$HOME/.trae/skills', '.trae/skills', '$HOME/.trae', '', '', ''],
  ['trae-cn', 'Trae CN', '$HOME/.trae-cn/skills', '.trae/skills', '$HOME/.trae-cn', '', '', ''],
  ['warp', 'Warp', '$HOME/.agents/skills', '.agents/skills', '$HOME/.warp', '', '', ''],
  ['windsurf', 'Windsurf', '$HOME/.codeium/windsurf/skills', '.windsurf/skills', '$HOME/.codeium/windsurf', '', '', ''],
  ['zed', 'Zed', '$HOME/.agents/skills', '.agents/skills', '$XDG_CONFIG_HOME/zed', '', '', ''],
  ['zcode', 'ZCode', '$HOME/.zcode/skills', '.zcode/skills', '$HOME/.zcode', '', '', ''],
  ['zencoder', 'Zencoder', '$HOME/.zencoder/skills', '.zencoder/skills', '$HOME/.zencoder', '', '', ''],
  ['zenflow', 'Zenflow', '$HOME/.zencoder/skills', '.zencoder/skills', '$HOME/.zencoder', '', '', ''],
  ['neovate', 'Neovate', '$HOME/.neovate/skills', '.neovate/skills', '$HOME/.neovate', '', '', ''],
  ['pochi', 'Pochi', '$HOME/.pochi/skills', '.pochi/skills', '$HOME/.pochi', '', '', ''],
  ['promptscript', 'PromptScript', '', '.agents/skills', '', '', '', ''],
  ['adal', 'AdaL', '$HOME/.adal/skills', '.adal/skills', '$HOME/.adal', '', '', ''],
  ['universal', 'Universal', '$XDG_CONFIG_HOME/agents/skills', '.agents/skills', '', '', '', '']
];
